"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
$hostname\
$localip\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$zig\
$dart\
$swift\
$terraform\
[](fg:color_blue bg:color_purple)\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$azure\
[](fg:color_purple bg:color_bg3)\
$conda\
$package\
$memory_usage\
$cmd_duration\
$sudo\
[](fg:color_bg3 bg:color_bg1)\
$jobs\
$battery\
$status\
$shell\
$time\
[](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_gray = '#928374'
color_pink = '#d3869b'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = ""
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = ""
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = ""
Amazon = ""
Android = ""
Arch = "Û∞£á"
Artix = "Û∞£á"
CentOS = ""
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:color_orange fg:color_fg0"
format = '[@$hostname ]($style)'
disabled = false

[localip]
ssh_only = false
style = "bg:color_orange fg:color_fg0"
format = '[/$localipv4 ]($style)'
disabled = false

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = " "
"Music" = "Û∞ùö "
"Pictures" = " "
"Developer" = "Û∞≤ã "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_metrics]
added_style = "fg:color_fg0 bg:color_aqua"
deleted_style = "fg:color_fg0 bg:color_aqua"
only_nonzero_diffs = true
format = '[[+$added]($added_style) [[-$deleted]($deleted_style) ](fg:color_fg0 bg:color_aqua)]($style)'
disabled = false

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[lua]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[terraform]
symbol = "Û±Å¢"
style = "bg:color_blue"
format = '[[ $symbol( $workspace) ](fg:color_fg0 bg:color_blue)]($style)'

[zig]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[dart]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[swift]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_purple)]($style)'

[kubernetes]
symbol = "‚ò∏"
style = "bg:color_purple"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_purple)]($style)'
disabled = false

[aws]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $profile)( $region) ](fg:color_fg0 bg:color_purple)]($style)'

[gcloud]
symbol = "Û±á∂"
style = "bg:color_purple"
format = '[[ $symbol( $account)( $region) ](fg:color_fg0 bg:color_purple)]($style)'

[azure]
symbol = "Û∞†Ö"
style = "bg:color_purple"
format = '[[ $symbol( $subscription) ](fg:color_fg0 bg:color_purple)]($style)'
disabled = false

[git_commit]
commit_hash_length = 7
style = "bg:color_aqua"
format = '[[ $hash ](fg:color_fg0 bg:color_aqua)]($style)'
only_detached = true

[git_state]
style = "bg:color_aqua"
format = '[[ $state( $progress_current/$progress_total) ](fg:color_fg0 bg:color_aqua)]($style)'

[sudo]
style = "bg:color_bg3"
format = '[[ $symbol ](fg:color_red bg:color_bg3)]($style)'
symbol = "üßô"
disabled = false

[status]
style = "bg:color_bg1"
format = '[[ $symbol $status ](fg:color_red bg:color_bg1)]($style)'
symbol = "‚úñ"
disabled = false

[shell]
fish_indicator = "Û∞à∫"
bash_indicator = ""
zsh_indicator = ""
style = "bg:color_bg1"
format = '[[ $indicator ](fg:color_fg0 bg:color_bg1)]($style)'
disabled = false

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[package]
symbol = "üì¶"
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg3)]($style)'

[memory_usage]
symbol = "üêè"
style = "bg:color_bg3"
format = '[[ $symbol( $ram) ](fg:color_fg0 bg:color_bg3)]($style)'
threshold = 70
disabled = false

[cmd_duration]
min_time = 500
style = "bg:color_bg3"
format = '[[ ‚è±Ô∏è $duration ](fg:color_fg0 bg:color_bg3)]($style)'

[jobs]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $number) ](fg:color_fg0 bg:color_bg1)]($style)'

[battery]
full_symbol = "üîã"
charging_symbol = "üîå"
discharging_symbol = "‚ö°"
unknown_symbol = "‚ùì"
empty_symbol = "ü™´"

[[battery.display]]
threshold = 10
style = "bg:color_bg1 fg:color_red"

[[battery.display]]
threshold = 30
style = "bg:color_bg1 fg:color_yellow"

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
